#%RAML 1.0 NamedExample

notebook:
  title: Bombs Rain on Bobtown
  owner: Bob
  content: 
    - page1
    - page2
    - page3

notebook-again:
  owner: Sally
  title: Money Rains on Bobtown
  content: 
    - page1
    - page2
