#%RAML 1.0 NamedExample
scenarioExample:
  playerRegistry:
    - one
    - two
  shipRegistry:
    - one
    - two
  colonyRegistry:
    - one
    - two
  bank:
    liquidBalance: 100
    totalBalance: 1000
    loans:
      - one
      - two
    bonds:
      - one
      - two
  notebooks:
    - one
    - two
  notes:
    - one
    - two
